Feature- Add Scroll to top functionality on route changes
henrylin03/eqa-martial-arts pull request #37
Opened 2024-12-29 10:37 UTC by ketansahugit

### Summary:
This pull request adds functionality to automatically scroll to the top of the page when navigating between routes. 

### Changes Made:
Introduced a `ScrollToTop` component that uses the `useLocation` hook to listen for route changes and triggers a `window.scrollTo(0, 0)` call.

Fixes #26

2024-12-29 23:16 UTC, henrylin03 requested changes
Hi, thanks for submitting the PR.

Any chance you can do this without using a `useEffect`? 

IIUC, `useEffect` should be only used when subscribing to an external source to deal with side-effects. Scrolling to the top doesn't seem to be a situation that we should use it, and introduces a code smell.

![image](https://github.com/user-attachments/assets/4f6eaea2-2e38-4055-bf00-d7107ef28853)

https://www.reddit.com/r/reactjs/comments/17q3d1l/thoughts_on_avoiding_useeffectusestate_when/

from memory, somewhere in the React Router docs there is some way to do this - can you have a look?

2024-12-29 23:17 UTC, henrylin03 commented
once you address, please request a new review - thanks for your help!

2025-01-01 18:21 UTC, ketansahugit commented
@henrylin03  I have replaced the ScrollToTop component with ScrollRestoration. What do you think? it seems to be working fine.

2025-01-02 03:28 UTC, henrylin03 approved these changes
approved!

adding docs for future reference: https://api.reactrouter.com/v7/functions/react_router.ScrollRestoration.html

2025-01-02 03:29 UTC, merged